In [1]:
import numpy as np

In [2]:
lista = [1,2,3]
array = np.array(lista)

In [3]:
array

array([1, 2, 3])

In [4]:
array[0]

np.int64(1)

In [5]:
np.arange(5,30,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [6]:
np.zeros(shape= (10,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
aleatorios = np.random.randint(0,100,50)

In [8]:
aleatorios

array([ 6, 96, 87, 11, 55, 16, 16, 19, 92, 79, 29, 85, 35, 92, 81, 50,  5,
       19, 34,  7, 57, 54, 86, 12, 29,  3, 72, 24, 53, 39, 74, 28, 59, 81,
       41, 56, 81, 79, 99, 95, 37, 23, 38,  9,  3, 71, 16, 39, 73, 52])

In [9]:
aleatorios.argmax()

np.int64(38)

In [10]:
aleatorios.max()

np.int64(99)

In [11]:
aleatorios.shape

(50,)

In [58]:
aleatorios.reshape(10,5)

array([[51, 65, 65, 51, 76],
       [21, 83, 32, 38, 44],
       [ 5, 18, 58, 78, 77],
       [83, 25, 97, 36, 82],
       [34, 75, 64, 79, 91],
       [ 7, 28, 29, 83, 31],
       [85, 18, 61, 93, 68],
       [63, 25, 17, 15,  0],
       [78, 32, 73, 85, 98],
       [ 4, 40, 61, 44, 70]])

In [60]:
aleatorios.shape

(50,)

In [62]:
aleatorios = aleatorios.reshape(10, 5)

In [64]:
aleatorios

array([[51, 65, 65, 51, 76],
       [21, 83, 32, 38, 44],
       [ 5, 18, 58, 78, 77],
       [83, 25, 97, 36, 82],
       [34, 75, 64, 79, 91],
       [ 7, 28, 29, 83, 31],
       [85, 18, 61, 93, 68],
       [63, 25, 17, 15,  0],
       [78, 32, 73, 85, 98],
       [ 4, 40, 61, 44, 70]])

In [66]:
aleatorios = aleatorios.reshape(10, 5)


In [68]:
aleatorios[0,0]

51